# Generated by Django 5.0.4 on 2024-04-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('age_range', models.CharField(max_length=10)),
                ('sdg_interest', models.CharField(max_length=100)),
                ('attendance_type', models.CharField(choices=[('Physical', 'Physical'), ('Virtual', 'Virtual')], max_length=10)),
                ('accommodation_needed', models.BooleanField()),
                ('academic_level', models.CharField(max_length=50)),
                ('academic_major', models.CharField(max_length=100)),
                ('how_hear_about_ysf', models.CharField(max_length=200)),
                ('contact_preference', models.CharField(max_length=200)),
                ('employment_status', models.CharField(max_length=100)),
                ('expectations', models.TextField()),
                ('shirt_size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=2)),
            ],
        ),
    ]
