# Generated by Django 5.0.4 on 2024-05-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ysf_backend', '0002_rename_registration_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='attendance_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='shirt_size',
            field=models.CharField(max_length=100),
        ),
    ]
